data:
  batch_size: 256
model:
  model_type: ModelType.MLP
mean_flow:
  use_optimal_transport: True
evaluation:
  num_train_epoch_per_evaluation: 1000
trainer:
  max_epochs: 20000
  fast_dev_run: False
  overfit_batches: 0.0
  lr: 0.001
  optim_method: "Adam"
